all:
  children:
    cisco_devices:
      hosts:
        sandbox_router:
          ansible_host: 10.10.20.50  # Your reserved sandbox IP
          # IMPORTANT: Many Cisco sandboxes use non-standard SSH ports
          # Common ports: 22 (default), 8181, 2222, 830 (NETCONF)
          # Check your DevNet sandbox "Access" tab for the correct port
          ansible_port: 22  # Change this if your sandbox uses a different port
          # For production, use vault variables instead:
          # ansible_user: "{{ vault_username }}"
          # ansible_password: "{{ vault_password }}"
          # ansible_become_password: "{{ vault_enable_password }}"
          ansible_user: developer
          ansible_password: C1sco12345
          ansible_network_os: ios
          ansible_connection: ansible.netcommon.network_cli
          ansible_become: yes
          ansible_become_method: enable
          # Additional connection settings for sandboxes
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=30'
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'  # Optional: skip host key check
        # Example: Load vault variables (uncomment and create vault/vault.yml)
        # vault_username: "{{ vault_username }}"
        # vault_password: "{{ vault_password }}"

    localhost:
      hosts:
        localhost:
          ansible_connection: local  # For testing without device